### ISSUE TITLE
No makefile in build after cmake

### ISSUE THREAD

**Issue by ManuelVargas1251** [markc/midicomp#2]
I've cloned the repo, created the build dir and ran 'cmake' successfully but no make file is created to run 'make' with. Am I missing something?

**Comment by markc** [comment]
Are you sure you did a `cd build` and then `cmake ..`? I just did this and got a Makefile...
```
total 24
drwxrwxr-x 1 markc markc   390 Mar 15 14:15 CMakeFiles/
-rw-rw-r-- 1 markc markc 11542 Mar 15 14:15 CMakeCache.txt
-rw-rw-r-- 1 markc markc  7803 Mar 15 14:15 Makefile
-rw-rw-r-- 1 markc markc  2143 Mar 15 14:15 cmake_install.cmake
```
However, typing make to complete the compile resulted in a whole bunch of yylex warnings but I did get a 57K `midicomp` binary that passed a few simple tests without crashing. FWIW I'm using KDE/Neon *buntu zesty with whatever versions of cmake/gcc/make it provides.

**Comment by ManuelVargas1251** [comment]
I did everything right, I just realized you're running this on linux and i'm running on windows so i'm getting msvs files instead. Thanks.
