### ISSUE TITLE
Segmentation fault while trying to convert a bunch of files

### ISSUE THREAD

**Issue by xhevahir** [markc/midicomp#4]
I'm trying to convert a directory full of MIDIs using this bash ``#!/bin/bash
FILES=/path/to/MIDIs
for i in $FILES;do midicomp ${i} > ${i}_output.txt; done`` but I'm getting the error Segmentation fault (core dumped). Am I doing something wrong?

**Comment by markc** [comment]
Try...

    find /path/to/MIDIs -type f | while read i; do echo "midicomp $i > ${i}_output.txt"; done

and if that looks okay then remove the echo and double quotes. Keep in mind it's recursive but it will handle a much larger number of files without overflowing any bash argument buffer.

**Comment by xhevahir** [comment]
Awesome, that worked! Converted thousands of MIDI files already. Thanks a lot for this program.

**Comment by markc** [comment]
Whew, good to hear that.

https://github.com/markc/midicomp/commit/dfc4262fd83f03ff2e102701f8a2bcc0b91f33d9
